### ISSUE TITLE
Use can-reflect to set attributes

### ISSUE THREAD

**Issue by matthewp** [canjs/can-view-autorender#5]
So it won't work with can-define: https://github.com/canjs/can-view-autorender/blob/master/can-view-autorender.js#L22

Posting from in the chat:

should there be a can/util/js/getter_setter or something that essentially does this:

``` js
exports.set = function(map, key, value){
  if(map.attr) {
    map.attr(key, value);
  } else if(map.set) {
    map.set(key, value);
  } else {
    map[key] = value;
  }
};
```

**Comment by phillipskevin** [comment]
This can use `canReflect.setKeyValue(map, key, value);` now.

**Comment by matthewp** [comment]
Fixed in https://github.com/canjs/can-view-autorender/pull/93
